name: Create and update release PR

on:
  push:
    branches:
      - release

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: echo $(gh --version)
      - run: |
          git fetch --all
          git branch -a
          echo $(git log remotes/origin/release..remotes/origin/master --pretty=format:"%h" | sed 's/^/- /')
      - name: Create release PR
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr create \
            --base master \
            --head release \
            --title "Release" \
            --body "$(git log release..master --pretty=format:"%h" | sed 's/^/- /')"
