name: Create and update release PR

on:
  push:
    branches:
      - release

env:
  BASE: master
  HEAD: release

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: echo $(gh --version)
      - id: get-pr-number
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          pr_number=$(gh pr list --base ${{ env.BASE }} --head ${{ env.HEAD }} --json number --jq '.[].number')
          echo "pr_number=$pr_number" >> "$GITHUB_OUTPUT"
      - id: build-pr-title
        run: echo "pr_title=Production release $(date +'%Y/%m/%d %H:%M:%S')" >> "$GITHUB_OUTPUT"
      - name: Create release PR
        if: ${{ !steps.get-pr-number.outputs.pr_number || steps.get-pr-number.outputs.pr_number == '' }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr create \
            --base ${{ env.BASE }} \
            --head ${{ env.HEAD }} \
            --title "Production release ${{ steps.build-pr-title.outputs.pr_title }}"
      - name: Update release PR
        if: ${{ steps.get-pr-number.outputs.pr_number != '' }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr edit ${{ steps.get-pr-number.outputs.pr_number }} \
            --title "Production release $(date +'%Y/%m/%d %H:%M:%S')"
