name: Create and update release PR

on:
  push:
    branches:
      - release

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: echo $(gh --version)
      - run: |
          echo $(git log remotes/origin/release..remotes/origin/master --pretty=format:"%h" | sed 's/^/- /')
      - name: Get PR number
        id: get-pr-number
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          pr_number=$(gh pr list --base master --head release --json number --jq '.[].number')
          echo "pr_number=$pr_number" >> "$GITHUB_OUTPUT"
      - run: echo ${{ steps.get-pr-number.outputs.pr_number }}
      - name: Create release PR
        if: ${{ !steps.get-pr-number.outputs.pr_number || steps.get-pr-number.outputs.pr_number == '' }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr create \
            --base master \
            --head release \
            --title "Release" \
            --body "Commit list(created_at DESC)\n$(git log remotes/origin/release..remotes/origin/master --pretty=format:"%h" | sed 's/^/- /')"
      - name: Update release PR
        if: ${{ steps.get-pr-number.outputs.pr_number != '' }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr edit ${{ steps.get-pr-number.outputs.pr_number }} \
            --body "$(cat << EOF
          Commit list(created_at DESC)
          $(git log remotes/origin/release..remotes/origin/master --pretty=format:"%h" | sed 's/^/- /')
          EOF
          )"
