name: Create and update release PR

on:
  push:
    branches:
      - release

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo $(gh --version)
      - name: Create release PR
        run: |
          gh pr create \
            --base main \
            --head release \
            --title "Release" \
            --body "$(git log develop..main --pretty=format:"%h" | sed 's/^/- /')"
