name: "Cron"
on:
  schedule:
    - cron: "*/10 * * * *"
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    name: debug
    runs-on: ubuntu-latest
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 1

      - name: Test
        run: |
          git fetch
          git branch -a

      - name: Fetch latest sha by current way
        run: |
          SHA=$(echo "$GITHUB_CONTEXT" | jq '.event.commits[].id' | tail -2 | head -1 | sed 's/\"//g')
          echo $SHA

      - name: Fetch latest sha by new way
        run: |
          git merge-base master origin/release
