name: "Cron"
on:
  # schedule:
  #   - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  deploy:
    name: debug
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test
        run: |
          echo ${{ github.event }}
          echo ${{ github.event_name }}

      - name: aaa
        run: |
          if [[ ${{ github.event_name }} = 'workflow_dispatch' ]]; then
            echo "schedule event"
          else
            echo "workflow_dispatch event"
          fi

      - name: get HEAD-1 sha
        run: |
          SHA=$(echo "$GITHUB_CONTEXT" | jq '.event.commits[].id' | tail -2 | head -1 | sed 's/\"//g')
          echo "image_tag=$SHA" >> $GITHUB_ENV
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
