name: "Cron"
on:
  schedule:
    - cron: "*/10 * * * *"
  push:
    branches:
      - master

jobs:
  deploy:
    name: debug
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: echo ${{ github }}

      - name: Test
        run: |
          echo ${{ github.event }}
          echo ${{ github.event_name }}

      - name: Fetch latest sha by current way
        run: |
          SHA=$(echo "$GITHUB_CONTEXT" | jq '.event.commits[].id' | tail -2 | head -1 | sed 's/\"//g')
          echo $SHA

      - name: Fetch latest sha by new way
        run: |
          git merge-base master origin/release
