name: httpreq

on: workflow_dispatch

jobs:
  httpreq:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -X POST 'https://27a5-240d-1a-d27-1500-30e3-a21-bd26-db67.jp.ngrok.io/events' \
            -H 'Content-Type: application/json' \
            -d '{"commit-hash":"${{ github.actor }}"}'

