name: "matrix object"
on:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        object: [{ name: "taro", age: 10 }, { name: "hanako", age: 12 }]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: |
          echo ${{ matrix.object.name }}
          echo ${{ matrix.object.age }}
