name: Create release pull request

on:
  workflow_dispatch:
  push:
    branches:
      - release

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 with:
        fetch-depth: 0
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0
    - name: Create a release pull request
      id: pr
      env:
        GIT_PR_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_PR_RELEASE_BRANCH_PRODUCTION: master
        GIT_PR_RELEASE_BRANCH_STAGING: release
        GIT_PR_RELEASE_TEMPLATE: .github/.git-pr-template
      run: |
        gem install -N git-pr-release
        git-pr-release --no-fetch --json > result.json
    - name: Set variables
      run: |
        created_at=$(cat result.json | jq .release_pull_request.data.created_at)
        updated_at=$(cat result.json | jq .release_pull_request.data.updated_at)
        pr_url=$(cat result.json | jq .release_pull_request.data.html_url)

        echo "created_at=$created_at" >> $GITHUB_ENV
        echo "updated_at=$updated_at" >> $GITHUB_ENV
        echo "pr_url=$pr_url" >> $GITHUB_ENV
    - name: Echo
      if: env.created_at == env.updated_at
      run:  echo 'hoge'

