name: 'Schedule Debug'
on:
  schedule:
    - cron:  '*/1 * * * *'

jobs:
  deploy:
    name: debug
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Test
      run: |
        echo ${{ github.actor }}
        echo ${{ github.event }}
        echo ${{ github.event_name }}
