name: "Schedule Debug"
on:
  schedule:
    - cron: "30 3 * * *"
  workflow_dispatch:

jobs:
  deploy:
    name: debug
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test
        run: |
          echo ${{ github.actor }}
          echo ${{ github.event }}
          echo ${{ github.event_name }}

      - run: |
          if [[ ${{ github.event_name }} = 'schedule' ]]; then
            echo "schedule event"
          else
            echo "workflow_dispatch event"
          fi
