name: test

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'name'
        required: true

env:
  LIST: ('kamillle' 'hoge')
  T_NAME: ${{ github.event.inputs.name }}

jobs:
  invoke:
    runs-on: ubuntu-latest
    steps:
    - name: Verify name is allowed
      run: |
        echo printf '%s\n' "${LIST[@]}
        echo `printf '%s\n' "${LIST[@]}" | grep -x ${T_NAME}`
        if printf '%s\n' "${LIST[@]}" | grep -qx ${T_NAME} > /dev/null >&2; then
          echo 'name is allowed'
        else
          echo 'name is not allowed'
          exit 1
        fi
