name: test

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'name'
        required: true

env:
  HOGE: 'kamillle'

jobs:
  invoke:
    runs-on: ubuntu-latest
    steps:
    - name: Verify name is allowed
      run: |
        list=('kamillle')

        if printf '%s\n' "${list[@]}" | grep -qx ${{ github.event.inputs.name }} > /dev/null >&2; then
          echo 'name is allowed'
        else
          echo 'name is not allowed'
          exit 1
        fi
