name: test

on:
  workflow_dispatch:
    inputs:
      hoge:
        description: "fuga"
        required: true
        type: choice
        options:
          - 01
          - 02
  push:
    branches:
      - master

jobs:
  invoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 300
      - run: |
          curl -fsSL https://mackerel.io/file/script/setup-apt-v2.sh | sh
          sudo apt-get install mkr
          mkr --version
      - run: |
          echo "branch_name=$(GITHUB_REF#refs/heads/)" >> $GITHUB_ENV

          echo ${GITHUB_REF#refs/heads/}
          echo ${GITHUB_REF}
      - name: echo last pr number
        run: |
          echo `git log --merges -n 1 | grep 'Merge pull request #' | awk '{ print $4 }' | sed 's/#//'`
      - name: current way
        run: |
          SHA=$(echo "$GITHUB_CONTEXT" | jq '.event.commits[].id' | tail -2 | head -1 | sed 's/\"//g')
          echo $SHA
      - run: |
          git fetch
          git branch -a
          git merge-base origin/master origin/release
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          number: 9
          message: |
            <details><summary><code>Show result</code></summary>

            ```
            nyaa
            ```

            </details>

            ---
